### PR TITLE
Normalize package names once with pkg.installed/removed using yum (bsc#1195895) - 3004

### PR DESCRIPTION
**Pull request by vzhestkov**
### What does this PR do?

On calling `pkg.installed` or `pkg.removed` the package name normalisation is performing few timess.
As the result it leads to removing `.ARCH` if used in the name of the package as suffix, but actually a part of the name.

### What issues does this PR fix or reference?
Port of PR for openSUSE-3000: https://github.com/openSUSE/salt/pull/496
Fixes: https://github.com/SUSE/spacewalk/issues/16974
Upstream PR: https://github.com/saltstack/salt/pull/62029

### Previous Behavior
Error on trying to install/remove the packages with such names:
`uptrack-updates-4.14.35-2047.502.4.el7uek.x86_64` (`x86_64` is not an arch there, but a part of the name, the arch of this package is `noarch`)
`weird-name-1.2.3-1234.5.6.test7tst.x86_64-20220214-2.1.noarch` (where `noarch` the real package arch and `x86_64` is a part of the name)

### New Behavior
No errors on installing/removing the package

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by meaksh — APPROVED** [review]

**Review by meaksh — COMMENTED** [review]
@vzhestkov I just noticed the upstream PR contains failing tests for centos and other yum based distros. Apparently those tests are around pkg testing so they might be related with your changes.

We are not getting those failures here on the test for this PR (probably because we test only in leap here), but I think we should clarify this first before merging this PR.

**Review by meaksh — CHANGES_REQUESTED** [review]
I'm requesting changes here until we clarify the question about upstream tests failing.

**Comment by vzhestkov** [comment]
@meaksh I've fixed the failing tests in upstream PR with slight adjustment the logic. Unfortunately these logic quite messy in `yumpkg` originally, so it's quite hard to fix it without harming all of the workarounds already existing in the code. I just finished checking on real test system, also looks fine.

**Review by meaksh — APPROVED** [review]
Thanks for fixing this. LGTM

**Comment by slsnow** [comment]
Thanks for all you guys do. Just wondering if you have any idea when this will hit maintenance updates? Thanks.

**Comment by vzhestkov** [comment]
It will be available with the next MU 4.3.1, but not sure about the exact dates. Probably at the end on July.

**Comment by juliogonzalez** [comment]
@vzhestkov check the release calendar ;-)

**Comment by vzhestkov** [comment]
@juliogonzalez calendar is reloading the page in infinite loop in my browser, have to reopen it with different one.
@slsnow seems it will be released at the beginning of September.

**Comment by slsnow** [comment]
Thanks.

**Pull request merged**
