### PR TITLE
Merge pull request #40894 from senthilkumar-e/broken_jobs_api_fix

### PR DESCRIPTION
**Pull request by edlane**
Backport from an upstream SaltStack commit for a SUSE issue reported here:
https://bugzilla.novell.com/show_bug.cgi?id=1087365

### CODE REVIEW

**Comment by brejoc** [comment]
@edlane I'm a bit confused. Is this still required? The bugzilla issue indicates, that some other packages is already shipping with this patch. For us 2016.11.4 has pretty much EOLed.

**Comment by edlane** [comment]
@brejoc,
This PR was requested by @rjschwei

**Comment by brejoc** [comment]
Hey @edlane, we've check this PR and it seems like all of the commits of this PR are already in `openSUSE:openSUSE-2016.11.4`. Could you please check this and close the PR if this is the case!? Thanks!

You can also verify with the OBS repo for `products:old/salt`: https://build.opensuse.org/request/show/610384

**Comment by edlane** [comment]
@brejoc ,
The reference you make appears only to have been included as a patch set **and NOT** as a commit to the openSUSE 2016.11.4 upstream repo itself.
A patch in the spec file is probably adequate but I am doing as directed by our team lead @rjschwei --presumably as "best practice".


-ed

**Comment by meaksh** [comment]
@edlane - The patches you see on the build service are all created based on the actual state of the `openSUSE-2016.11.4` branch. You can actually see all those commits here in the branch history: https://github.com/openSUSE/salt/commits/openSUSE-2016.11.4

**Comment by edlane** [comment]
@meaksh ,
Ah! now I see that it got applied back on April 25 -- Thanks!

**Comment by meaksh** [comment]
@edlane - Welcome! I'm closing this issue now. Thanks :+1:

**Pull request closed without merging**
