### PR TITLE
Make pass renderer configurable & other fixes

### PR DESCRIPTION
**Pull request by dmach**
More details in upstream PR https://github.com/saltstack/salt/pull/62120

### CODE REVIEW

**Review by meaksh — COMMENTED** [review]
Thanks for this PR! The code looks good to me +1

It would be definetely great that you could also provide some tests here.

**Comment by meaksh** [comment]
@darix @dmach you need to provide some unit tests that cover this new functionality in order to get the upstream PR and this one merged: 

Any chance to implement them? Thanks!

**Comment by dmach** [comment]
@meaksh sorry for a late response, I was unavailable for a while.
To be honest, I tried writing the tests several times already and always failed.
I'll try again, but I may need some guidance on how to write tests for salt.

**Comment by dmach** [comment]
@meaksh could you check if the tests look good to you?

A note for anyone who might be interested in quickly testing my changes (or running a salt test quickly).
Running `nox` is quite slow due to installing many unnecessary packages into a virtual env.
I hacked it by doing this:
```
cp requirements/base.txt requirements/static/ci/py3.10/linux.txt
cat requirements/pytest.txt >> requirements/static/ci/py3.10/linux.txt
nox -e 'pytest-tcp-3(coverage=False)' -- tests/pytests/unit/renderers/test_pass.py -v
```

**Comment by dmach** [comment]
I've force-pushed the patches from https://github.com/saltstack/salt/pull/62120 that were accepted by upstream already.

**Pull request merged**
