### PR TITLE
zypperpkg: ignore retcode 104 for search()

### PR DESCRIPTION
**Pull request by aplanas**
Fix bsc#1159670

### CODE REVIEW

**Comment by aplanas** [comment]
https://github.com/saltstack/salt/pull/58552

**Comment by aplanas** [comment]
https://github.com/saltstack/salt/pull/58552

**Review by isbm — APPROVED** [review]
Now from my side this looks good. Maybe @meaksh can add something.

**Comment by brejoc** [comment]
@aplanas Is there an upstream PR for this?

**Comment by aplanas** [comment]
@brejoc yes, is referenced in the second comment (https://github.com/saltstack/salt/pull/58552)

**Pull request merged**
