### PR TITLE
Backport #46867 string arg normalization (bsc#1094960)

### PR DESCRIPTION
**Pull request by isbm**
Backport #46867 string arg normalization (bsc#1094960)

### CODE REVIEW

**Comment by mcalmer** [comment]
Either merge or close it.

**Comment by isbm** [comment]
@mcalmer someone please kick @brejoc finally. :laughing:

**Comment by brejoc** [comment]
Sorry, I must have lost track of this after my vacation. So we are talking about [this PR](https://github.com/saltstack/salt/pull/46867) here!? Do we really need this or is it just a nice to have? I'm asking, because our `2016.11.4` is in hibernate and we don't want to wake it up so often. :wink:

**Comment by isbm** [comment]
@brejoc yes, this is only to 2016.11.4 version [because of the report](https://bugzilla.suse.com/show_bug.cgi?id=1094960#c27). Since we do support 2016.11.4 and it will be for a while, this needs to be backported.

**Comment by brejoc** [comment]
Closing, since I've cherry-picked the changes.

**Pull request closed without merging**
