### PR TITLE
 Fix base requirements for some dependencies versions (bsc#1211612)

### PR DESCRIPTION
**Pull request by meaksh**
### What does this PR do?

This PR fixes the base requirements for Salt to avoid dependencies versions problems when using `pkg_resources` to resolve and validate Salt package dependencies, as the defined versions restrictions in the generated `requires.txt` file are incompatible with the installed versions of these dependencies. We only see this inconsistency raising when using `pkg_resources` Python module to discover modules and dependencies, as with normal RPM packaging, this is not an issue.

This inconsistency is currently causing issue when running `ceph-salt` using Salt 3006.0:

```console
Traceback (most recent call last):                                                                
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master   
>     ws.require(__requires__)                                                                      
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require         
>     needed = self.resolve(parse_requirements(requirements))                                       
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve         
>     raise VersionConflict(dist, req).with_context(dependent_req)                                  
> pkg_resources.ContextualVersionConflict: (pyzmq 17.1.2 (/usr/lib64/python3.6/site-packages), Requirement.parse('pyzmq>=20.0.0'), {'salt'})
>                                                                                                   
> During handling of the above exception, another exception occurred:                               
>                                                                                                   
> Traceback (most recent call last):                                                                
>   File "/usr/bin/ceph-salt", line 6, in <module>                                                  
>     from pkg_resources import load_entry_point                                                    
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3123, in <module>       
>     @_call_aside                                                                                  
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3107, in _call_aside    
>     f(*args, **kwargs)                                                                            
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3136, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()                                                      
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 580, in _build_master   
>     return cls._build_from_requirements(__requires__)                                             
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())                                                       
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve         
>     raise DistributionNotFound(req, requirers)                                                    
> pkg_resources.DistributionNotFound: The 'pyzmq>=20.0.0' distribution was not found and is required by salt
```
After fixing this issue, similar exceptions are raised for `pycryptodomex` and `packaging`, as versions in `requires.txt` are incompatible with the installed versions, via RPM of the dependencies.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by agraul — COMMENTED** [review]
The bug report and pull request only  mention `pyzmq`, why are packaging and `pycryptodomex` also changed? Can you elaborate on that?

In Slack you mentioned a `requires.txt` and `pkg_resources`, while the PR does not change a `requires.txt` file or anything called `pkg_resources`, can you explain how this PR fixes the problem you described in Slack?

Other than that, it would be great if the commit message would follow https://cbea.ms/git-commit.

**Comment by meaksh** [comment]
> The bug report and pull request only mention `pyzmq`, why are packaging and `pycryptodomex` also changed? Can you elaborate on that?
> 

The fix and bug report initially started with the `pyzmq` issue but after fixing it, other exceptions appeared regarding `pycryptodomex` and `packaging`. Same issue: version conflict between generated `requires.txt` file and installed versions.

So I just added those extra fixes to the PR. I should had adjusted PR description properly. Will do.

> In Slack you mentioned a `requires.txt` and `pkg_resources`, while the PR does not change a `requires.txt` file or anything called `pkg_resources`, can you explain how this PR fixes the problem you described in Slack?
> 

The `requires.txt` file that is provided as part of Salt egginfo is generated during package building, by `setup.py`, based on the defined requirements in these files I'm changing on this PR: https://github.com/openSUSE/salt/blob/openSUSE/release/3006.0/setup.py#L114

Even if we had a `requires.txt` with some inconsistent versions, that doesn't affect us in the context of our RPM requires, but it affects someone using `pkg_resources` Python module: https://setuptools.pypa.io/en/latest/pkg_resources.html when discovering packages and dependencies (as it is the case with `ceph-salt`).

In the end, I want `pkg_resources` is able to resolve and validate the dependencies for Salt 3006.0, so this command is not producing any exception:

```console
python3 -c 'import pkg_resources; print(pkg_resources.working_set.resolve(pkg_resources.working_set.by_key["salt"].requires()))'
```

> Other than that, it would be great if the commit message would follow https://cbea.ms/git-commit.

I'll adjust it better. Thanks for the review and suggestions!

**Review by agraul — APPROVED** [review]
Thanks for the explanation, makes sense! I'm sometimes a bit lost in the Python packaging ecosystem, there are just so many parts working together which are also changed again and again...

Thanks for updating the commit message as well, looks good!

**Comment by meaksh** [comment]
Merging PR now since ongoing tests already pass before changing commit message.

**Pull request merged**
