### PR TITLE
Fix bug/issue #540

### PR DESCRIPTION
**Pull request by raulillo82**
### What does this PR do?
Fixes pkg.version_cmp on openEuler systems (and a few other os flavors that were affected as well).

### What issues does this PR fix or reference?
Fixes: #540

### Previous Behavior
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1916, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1873, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
        return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/yumpkg.py", line 685, in version_cmp
        return __salt__["lowpkg.version_cmp"](pkg1, pkg2, ignore_epoch=ignore_epoch)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__
        return self.value()[item]
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 334, in __getitem__
        super().__getitem__(item)  # try to get the item from the dictionary
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__
        raise KeyError(key)
    KeyError: 'lowpkg.version_cmp'
ERROR: Minions returned with non-zero exit code

uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler
```

### New Behavior
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    1
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by raulillo82** [comment]
Related test passes successfully:

```
(salt) raul@laptop:~/gh-forked-projects/saltstack/salt-1>  (fix_issue_62248)$ python3 -m nox -e "pytest-3.7(coverage=False)" -- tests/pytests/unit/modules/test_rpm_lowpkg.py
nox > Running session pytest-3.7(coverage=False)
nox > Re-using existing virtual environment at .nox/pytest-3-7-coverage-false.
nox > Session pytest-3.7(coverage=False) was successful.
nox > Running session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False)
nox > Re-using existing virtual environment at .nox/pytest-parametrized-3-7-crypto-none-transport-zeromq-coverage-false.
nox > python -m pip install --progress-bar=off -U 'pip>=20.2.4,<21.2' 'setuptools!=50.*,!=51.*,!=52.*,<59' wheel
nox > python -m pip install --progress-bar=off -r requirements/static/ci/py3.7/linux.txt
nox > python -m pytest --rootdir /home/raul/gh-forked-projects/saltstack/salt-1 --log-file=/home/raul/gh-forked-projects/saltstack/salt-1/artifacts/logs/runtests-20220630130202.869038.log --log-file-level=debug --show-capture=no -ra -s --showlocals --transport=zeromq tests/pytests/unit/modules/test_rpm_lowpkg.py
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.0, pytest-7.0.1, pluggy-0.13.0
tempdir: /tmp/stsuite
max open files; soft: 3072; hard: 524288
rootdir: /home/raul/gh-forked-projects/saltstack/salt-1, configfile: pytest.ini
plugins: skip-markers-1.2.0, helpers-namespace-2021.4.29, tempdir-2019.10.12, system-statistics-1.0.2, shell-utilities-1.4.0, salt-factories-1.0.0rc17, timeout-1.4.2, subtests-0.4.0, httpserver-1.0.4, flaky-3.7.0
collected 19 items                                                                                                                                                                                              

tests/pytests/unit/modules/test_rpm_lowpkg.py ............s.s....

============================================================================================ short test summary info ============================================================================================
SKIPPED [1] tests/pytests/unit/modules/test_rpm_lowpkg.py:232: The RPM lib is not installed, skipping
SKIPPED [1] tests/pytests/unit/modules/test_rpm_lowpkg.py:226: The rpmdev-vercmp binary is not installed
========================================================================================= 17 passed, 2 skipped in 1.00s =========================================================================================
nox > Session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False) was successful.
nox > Ran multiple sessions:
nox > * pytest-3.7(coverage=False): success
nox > * pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False): success

```

**Comment by raulillo82** [comment]
Tests passed successfully:

```
(salt) raul@laptop:~/gh-forked-projects/opensuse/salt>  (fix_issue_540)$ python3 -m nox -e "pytest-3.7(coverage=False)" -- tests/pytests/unit/modules/test_rpm_lowpkg.py 
nox > Running session pytest-3.7(coverage=False)
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/pytest-3-7-coverage-false
nox > Session pytest-3.7(coverage=False) was successful.
nox > Running session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False)
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/pytest-parametrized-3-7-crypto-none-transport-zeromq-coverage-false
nox > python -m pip install --progress-bar=off -U 'pip>=20.2.4,<21.2' 'setuptools<50.*' wheel
nox > python -m pip install --progress-bar=off -r requirements/static/ci/py3.7/linux.txt
nox > python -m pytest --rootdir /home/raul/gh-forked-projects/opensuse/salt --log-file=artifacts/logs/runtests-20220630132258.170274.log --log-file-level=debug --show-capture=no -ra -s --transport=zeromq tests/pytests/unit/modules/test_rpm_lowpkg.py
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.0, pytest-6.1.2, py-1.10.0, pluggy-0.13.0
tempdir: /tmp/stsuite
max open files; soft: 3072; hard: 524288
rootdir: /home/raul/gh-forked-projects/opensuse/salt, configfile: pytest.ini
plugins: tempdir-2019.10.12, subtests-0.4.0, salt-factories-0.121.1, helpers-namespace-2019.1.8, flaky-3.7.0
collected 25 items                                                                                                                                                                                              

tests/pytests/unit/modules/test_rpm_lowpkg.py ............s............

=============================================================================================== warnings summary ================================================================================================
salt/ext/tornado/web.py:1874
  /home/raul/gh-forked-projects/opensuse/salt/salt/ext/tornado/web.py:1874: DeprecationWarning: invalid escape sequence \.
    """

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================================================ short test summary info ============================================================================================
SKIPPED [1] tests/pytests/unit/modules/test_rpm_lowpkg.py:233: The RPM lib is not installed, skipping
=================================================================================== 24 passed, 1 skipped, 1 warning in 1.00s ====================================================================================
nox > Session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False) was successful.
nox > Ran multiple sessions:
nox > * pytest-3.7(coverage=False): success
nox > * pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False): success
```

**Comment by meaksh** [comment]
@raulillo82 thanks for the contributions! 

We would need an upstream Salt PR before we can get this one accepted into our Salt package. Do we have this upstream PR created already?

Thanks!

**Comment by raulillo82** [comment]
@meaksh see https://github.com/saltstack/salt/pull/62249 (hope i linked the right one).

**Comment by raulillo82** [comment]
> @raulillo82 thanks for the contributions!
> 
> We would need an upstream Salt PR before we can get this one accepted into our Salt package. Do we have this upstream PR created already?
> 
> Thanks!

It is merged upstream. Can this one be merged now?

**Comment by raulillo82** [comment]
> @raulillo82 thanks for the contributions!
> 
> We would need an upstream Salt PR before we can get this one accepted into our Salt package. Do we have this upstream PR created already?
> 
> Thanks!

It is merged upstream now. @meaksh may this one be merged now? Thanks!

**Review by meaksh — APPROVED** [review]

**Pull request merged**
