### PR TITLE
Fixed parsing of master minion returns when batching is enabled

### PR DESCRIPTION
**Pull request by grahamhayes**
This fixes https://bugzilla.suse.com/show_bug.cgi?id=1038814 for the CaaSP product, as we use the orchestration runner to install and update our install.

### CODE REVIEW

**Comment by isbm** [comment]
Please open this PR in upstream instead! Thanks.

**Comment by grahamhayes** [comment]
This is for the openSUSE product - for a team in SUSE using this package. an email was sent to the list about it.

This has been fixed upstream already - this just brings the patch back to our package.

**Comment by ajaeger** [comment]
This is a backport of https://github.com/saltstack/salt/pull/40905, please reconsider, @isbm

**Comment by isbm** [comment]
@ajaeger ah, OK. Although it is P1, yet since this is not an L3, I would ask where are the unit tests for it? Because we would like to have _every_ patch tested.

**Comment by grahamhayes** [comment]
@isbm this is a clean backport of an upstream PR (I literally just `git cherry-pick <sha>`'d it on to this branch). I can add unit tests, but I would have to spend a lot of time figuring out how the salt test harness works, and they should really go upstream before we add them here.

**Comment by isbm** [comment]
@grahamhayes That is the problem: "clean backport from upstream" != "clean support of Salt in SLE". You basically say to us to do these tests ourselves instead of you.

**Comment by kkaempf** [comment]
Adding @moio since the title mentions "minion returns" and "batching" :wink:

**Comment by isbm** [comment]
@kkaempf right. Although I know why, because I wrote that recursive part in Utils they're just using now... :smile:

**Comment by pkazmierczak** [comment]
@isbm I vote UT too.

**Comment by eotchi** [comment]
We **really** need this in the next maintenance update. Without it, the scalabity of our deployments is highly compromized. As the maintenance update is getting finalized as we speak, could we agree on having this accepted now and we commit to provide tests as soon as possible?

**Comment by kiall** [comment]
Also, FYI, I spoke with Graham and he is currently looking at how the testing is done etc to write up a test case.

**Comment by isbm** [comment]
@eotchi sure. Here only Unit test is needed, not an integration test. Salt Toaster will run them (UTs) as well. This can be done in an hour for a beginner. :-)

**Comment by isbm** [comment]
@pkazmierczak @meaksh @dincamihai OK, @eotchi called this _really urgent_, so I am accepting this, as this is critical state. However, @grahamhayes owes us an UT for it. :wink:

**Pull request merged**
