### PR TITLE
virt.volume_info fixes

### PR DESCRIPTION
**Pull request by cbosdo**
Backport saltstack/salt#52033 which is a fix for PR #129

### CODE REVIEW

**Comment by dincamihai** [comment]
We need to merge this with https://github.com/openSUSE/salt/pull/129, forcepush 2019.2.0 and update the patch in OBS

**Comment by cbosdo** [comment]
@dincamihai any news on this PR?

**Comment by dincamihai** [comment]
@cbosdo sorry, this got out of our sight for a while. I'll try to incorporate it today. Thanks for the reminder!

**Comment by dincamihai** [comment]
Incorporated into https://github.com/openSUSE/salt/commit/5e202207d02d2bf4860cc5487ed19f9d835993d1. Closing this PR. Thanks, @cbosdo !

**Comment by dincamihai** [comment]
SR: https://build.opensuse.org/request/show/689429

**Comment by cbosdo** [comment]
master-port: saltstack/salt#55165

**Pull request closed without merging**
