### PR TITLE
Add unit tests to Pull Requests

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
### What does this PR do?

Add github actions for running unit tests at the Pull Request. This way,
we cannot merge if those tests fail and so we keep the unit tests green
in master.

### What issues does this PR fix or reference?

https://github.com/SUSE/spacewalk/issues/14221

### Previous Behavior

Unit tests were not run at the PR

### New Behavior

Unit tests run at the PR

### Tests written?

N/A

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
See an example at https://github.com/jordimassaguerpla/salt/pull/1

**Review by meaksh — APPROVED** [review]
This is great! Thanks a lot!

I'll merge this shortly :+1:

**Comment by jordimassaguerpla** [comment]
@meaksh I added the "SKIP_TAG" in the commit subject (per https://github.com/openSUSE/git-packaging-tools/pull/10)

**Comment by meaksh** [comment]
@jordimassaguerpla the default skip tag would be `[skip]`, could you reword the commit?

Thanks in advance!

**Comment by jordimassaguerpla** [comment]
@meaksh done ;)

**Pull request merged**
