### PR TITLE
Option to en-/disable force refresh in zypper

### PR DESCRIPTION
**Pull request by darix**
### What does this PR do?

Adds option to turn off force refresh

### What issues does this PR fix or reference?

#213

### CODE REVIEW

**Comment by brejoc** [comment]
@darix Should we push this upstream too?

**Comment by darix** [comment]
Anything blocking the merge?

**Comment by brejoc** [comment]
@darix Sorry for the delay, but most of our resources where blocked by the Salt3000 preparations. We are currently opening PRs at upstream to get at least a weather forecast on the changes. Sometimes they'd like to see additional changes and then we'd have to update our patches again, because otherwise we'd diverge. So once we've got at least a :+1: from upstream, we can merge this and proceed.

**Comment by agraul** [comment]
The upstream PR for this change can be found at https://github.com/saltstack/salt/pull/56419

**Comment by brejoc** [comment]
Let's wait for them to give a thumbs up and then we can proceed here.

**Comment by darix** [comment]
it is merged \o/

**Comment by brejoc** [comment]
@agraul Did you check if we have https://github.com/saltstack/salt/pull/54954? Apart from that we are green here!

**Comment by darix** [comment]
I have a patch locally that is on top of the root param patch.

osc rdiff openSUSE:{Factory,infrastructure}/salt

**Comment by agraul** [comment]
@brejoc I just did a quick check, it looks like that PR is already covered.

**Pull request merged**
