### PR TITLE
Backport from develop features required by yomi

### PR DESCRIPTION
**Pull request by aplanas**
* Add root and no_recommends parameters in the public interface for Zypper and RPM (lowpkg)
  https://github.com/saltstack/salt/pull/50125

* Add root parameter to useradd, shadow and groupadd
  https://github.com/saltstack/salt/pull/50175

* cmd: Add root parameter for wait and run states
  https://github.com/saltstack/salt/pull/50302

* systemd: add optional root parameter
  https://github.com/saltstack/salt/pull/50380

* Add new chroot module
  https://github.com/openSUSE/salt/pull/50418

* Add new module freezer
  https://github.com/saltstack/salt/pull/50452

* btrfs: add all subvolume commands
  https://github.com/saltstack/salt/pull/50541

* btrfs: add new btrfs state
  https://github.com/saltstack/salt/pull/50635

* zypper: demote log from error to warning
  https://github.com/saltstack/salt/pull/50671

* blkid: add search by token
  https://github.com/saltstack/salt/pull/50706

* mount: add fstab_{present,absent} states 
  https://github.com/saltstack/salt/pull/50725

* btrfs: add option to not set subvolumes as default
  https://github.com/saltstack/salt/pull/50801

* Add disk_set and disk_toggle functions, and update valid partition flags
  https://github.com/saltstack/salt/pull/50834

* disk: support setting FAT size for format_
  https://github.com/saltstack/salt/pull/51074

* parted: fix set_ valid flags comment.
  https://github.com/saltstack/salt/pull/51704

* grains/core: ignore HOST_NOT_FOUND errno in fqdns()
  https://github.com/saltstack/salt/pull/51706

* cmdmod: add 'binds' parameter in run_chroot
  https://github.com/saltstack/salt/pull/51871

* mount: fix extra -t parameter
  https://github.com/saltstack/salt/pull/51905

* lvm: be quiet when a pv, lv or vg is not expected
  https://github.com/saltstack/salt/pull/51929

* linux_lvm: clean error in pvcreate and pvremove
  https://github.com/saltstack/salt/pull/51954

* blockdev: hide blkid errors when are expected
  https://github.com/saltstack/salt/pull/51956

* partially unify public functions signature for pkg and lowpkg
  https://github.com/saltstack/salt/pull/51973

* extmods: add utils directories in sys.path
  https://github.com/saltstack/salt/pull/52001

### CODE REVIEW

**Comment by kkaempf** [comment]
Why are so many changes needed where most of them show as "merged" upstream ?

**Comment by aplanas** [comment]
@kkaempf All the patches are merged in the develop branch, no one is under review or do not comes from any other source that is not upstream.

I backported all of them to 2019.2 upstream branch, but this backport is indeed too late, as they are in rc2. Somehow I didn't realize that having the code in develop is not enough to have the code landed in fluorine. I will work with upstream about this.

Meanwhile I would like to include the patches in our package, and after asking the salt team I understand that I need to squash all the commits in a single pull request, that needs to land to openSUSE-2018.3.0. But looks like that this is not possible, as my changes depends on some changes that are not in this branch. So makes sense to use this openSUSE-2019.2.0rc1 branch that is very similar to where my backport proposal is in upstream.

If this is not correct, tell me the correct way and I will adjust the patch.

**Comment by dincamihai** [comment]
@aplanas we updated to 2019.2.0rc2 and I have re-targeted your PR to the new branch. Could you please rebase your branch on top of that? (openSUSE-2019.2.0rc2)

**Comment by aplanas** [comment]
Any progress that this will be merged? I saw the release note today.

**Comment by aplanas** [comment]
I want to rebase this, is still the rc2 branch the correct one, or do I need to use openSUSE-2019.2.0?

**Comment by dincamihai** [comment]
> I want to rebase this, is still the rc2 branch the correct one, or do I need to use openSUSE-2019.2.0?

It's openSUSE-2019.2.0 now. Thanks!

**Comment by aplanas** [comment]
@dincamihai done

**Pull request closed without merging**
